logger:
  file:
    path: /var/log/open5gs/smf.log
  level: info

global:
  max:
    ue: 1024

smf:
  sbi:
    server:
      - address: 10.45.0.21
        port: 7777
    client:
      nrf:
        - uri: http://10.45.0.11:7777
  pfcp:
    server:
      - address: 10.45.0.21
    client:
      upf:
        - address: 10.45.0.30
  gtpc:
    server:
      - address: 10.45.0.21
  gtpu:
    server:
      - address: 10.45.0.21
  session:
    - subnet: 10.45.1.0/24
      gateway: 10.45.1.1
      dnn: internet
  dns:
    - 8.8.8.8
    - 1.1.1.1
  mtu: 1400
  info:
    - s_nssai:
        - sst: 1
          sd: "000001"
          dnn:
            - internet
