logger:
  file:
    path: /var/log/open5gs/udm.log
  level: info

global:
  max:
    ue: 1024

udm:
  sbi:
    server:
      - address: 10.45.0.23
        port: 7777
    client:
      nrf:
        - uri: http://10.45.0.11:7777
